sudo: true
language: python
python:
- '3.6'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
services:
- docker
before_install:
- cd backend
- echo $TOKEN | gpg --passphrase-fd 0 credentials.tar.gz.gpg
- tar -xzf credentials.tar.gz
- rm credentials.tar.gz
install:
- python -m pip install -e .
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest --cov=./ --show-progress
- pipenv run coveralls
before_deploy:
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud --quiet components update
deploy:
- provider: script
  script: chmod +x $TRAVIS_BUILD_DIR/backend/backend-deploy-production.sh && sh $TRAVIS_BUILD_DIR/backend/backend-deploy-production.sh
  skip_cleanup: true
  on:
    branch: deploy
env:
  global:
  - secure: hbQtNjePydPtwCDVLffHWR2ns7JPkbQyjf0dAJL2b/5qSNg+OncI0WByR+H6OFDbGMsJpKUQuWmAd3vYA/vrO8gImCbtAdqb1pBGBjpCe7N7cpCZKbToQ7CHRfYZjz1nUQP+4Wgm2mRL+ir4GnRQi2A4ArvkaXT41dff+yqkCehSVezbL1RDRuKHz6dDjkTGQQP7vuZx8XeAhmubhjecGoZGLUsxqQzcWenqwmHl5Ny5fqKlpNO3aRhgxwp7dZSpVk2A1i52yH9GgUxMo5WaP6hNSy+hkAEEsBGCEZ8/z+co/SxMZUVs/42RC8Cb45DblXETxITPW+hJ6MBxdvqrD4dKaFNixv83W1Iat4A7PXPWOCRGFP0e4D/UG6OAedGJdt1Pluc56W1PJTStQAb4d0A5F7m/TPRgSKDzyIpjYjRSUvjGoe6KB1y2d3Rt+TejUsljoBK7AC0GOupS91WAAQVUXVPbiWD84DNmy4p/oULUGXfY8QyFEkysfE7EEa4aUoxW1Gz7QyL8kIYUGiDho7EvQ6PaoKM6Ufc/zdA93O55cfXv70BRgXaCf1ipCk3wcPUlDRvOfIb5u6rEpcILbgrj1fndFDKJ8SdL9eGn3xNNqmfI5O/7psH0C+rlrN3NiOqYhBe/gUg8b8PbG2CG9R3LoOThnAoTX/sTkeO8dho=
  - secure: uTp2ff/JBl6q0MNLEzGUDuEXnji5LOPseOO8cQyTQlfMf01HOiqrF6IzvlSCs4zFCoYEA7HRq/HytdnJcvOZKI0Tct0bBwbWgBRRTB/U6Q6LZDgckzFh+ScOxfBht+F8f1hJDX+MW2LfsVBrEFSQM7o0mOX8OytGloA/6lTq4avtqWrMqUqAZE3cmKHXoRUF6KO6hNEr+G4UtwC4Ez4M0r5FBkLXUcymN2ujGqW5f29UbCIrkHML01FRAYN8YpfBwkfOymUwRST81PDqzZ/JquHz91UeRvNRoRwGvcv+kRKqojtCSVA2SLePFPvfWtTBdovZ018cuwCkrKZM8XVwWhuFWBW9Om7PdMbLlEoZIZCfdQeDx2cIG7tghG7j5kcq9T1B3h0ssL0NcSbP6eWdYlocktcdaKZ4stctT01OTWzord5oLV7VUW3vT5z3pLuNBZYQj/K7QZ+tapOUj66gtOQpfjjUsAcF54eD9aPY9n4Dl+FD5eo+U7z6JSN9HZMs6dzBC8wQLl1XnlCCDO0K30EqW0B5G19g/9VrjaiHuedAHyc+Iy1H4AIqbixvuQ46ZUpuKpbqGQbBP9pxoMbLWD/HvJ1Qx2a0V2h02pDCJyZM7exVR/WaxsGwFltIAXWkZn70QrtOSaMnfD4gvVFkC709jvdm6msKmsPT70IB/UY=
  - secure: j30k0pVrwF+RBbzYfGLs/iJYFqA4Q3avjOlU3dlROgivY55yiGxpTxEyM5qHWYzlBA57dUdT8OhbPmBlMOGRHE5TgQ5iYHHpafekYr+6TkhzIGv+dxQMgpEwTPOyrdHI89Ap95OxYO7HeRrC8tSmRUmvC5qmY0YneWJH+lLaV4J+BDABVKul0CkDKwZ/yLx9c64J3KoogEB26iqxbgxsKSH9W11v7z57cBcBVw0b3ULkjXIGlNVvpLrzfvQhsfv7ViimAJXStfZiN1W5g+m5qvSEwziGH4xgngoVx1aoZtUNTxO8RdYrvPzXymxtCeNUblRlaBTbqMfsI8YEEkyejEX+tzEMpwihxRttmWqr2KqNtna8F6AB778v2upKswt7kAaxXnlwD2KzyXuEWjvVahFJiubLugaJgQ/+9/xksrwWA1YpnElLqX7UlZCI04XTjcz4IjXM8VCU8l1kP4bDC4a/Uozrx3qGZp6cbPa5GdrOWtFuaB0Dg0Qck6PxVaqlH9PVtzdBhVDBZwKR0MfGRcyOujrpPtJFixZr1jwE4qGQkSAnCPKRprr5LsfwmUVMLK+S+Xxha4FVdmWOZmaj+EjtctSuDvZK/nePP1MHVS7KEsExxU6anEONqo27xcw7VBED/NnkweHBMMRq0T78M3F+i5acybhnq9N0DNoqpxU=
  - secure: RzJxnhZEocYgNGBl6viK/g1RNkLkq/gvanPpSYyWg4TrH9lwRLu+q2dJUg0lYlm8aIKReYvltLEHdhOvtGd7hdcGZHd0dl2DCxG8cBcDU21rH68YSuxx1YhckreP0Fc4SylrxhNGGwxSsIF66iBpGbv4XY7dNKI6GU+NxT1oyvFlLvhKjrKEWNbBEPeOrx0mV6O2/STuip3XlP7x0l2CXUvxjfoCWzvmdgyoMNAAP6no4caPBHznP1+CioFYFyqG47ChT2MYVGCk0ywNRdqwEy2UHJew6TZeC9mKeWbg9nKCTWfZgC3NT2MhcBVhPWO4BJnNszYjLFxCSevjAuLRwSoU4IQI67N9Hl3DVte9fhVZWXv1Gubm2ja/BeTUFpQIRVKI/bxtv8O3h9HBIFb61HfbCsifgpma6N9GPfUMRRUGyCNFnb7TvRy8vMW5fcvQfKqOpQZiOKZz00UD4k/PmEtrJZXZL4Sw3Bz8rZZ6ahy3cl73XBui3FMShwzgQnNBie5LqPY21DovCn+mzn3/rPCiygFDVUDa9YBxZTNlrC8Twlsex+YYkJrNUiO3hR4DvzPOjZbrAVN/+EQN1RmDCfUMVbCliFAa/kBTKKx4aTWvFAheXch/UFYlROFZT6spvea2w/El3Lo+5R3mGvKnrqovrPJR7RNXwnIWERwFIcQ=
