language: python
python:
- '3.6'
#before_install:
# encryption goes here
install:
- "cd backend"
- python -m pip install -e .
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest --cov=./ --show-progress