sudo: true
language: python
python:
- '3.6'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
services:
- docker
before_install:
- cd backend
- echo $TOKEN | gpg --passphrase-fd 0 credentials.tar.gz.gpg
- tar -xzf credentials.tar.gz
- rm credentials.tar.gz
install:
- python -m pip install -e .
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest --cov=./ --show-progress
- pipenv run coveralls
before_deploy:
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud --quiet components update
deploy:
- provider: script
  script: chmod +x $TRAVIS_BUILD_DIR/backend/backend-deploy-production.sh && sh $TRAVIS_BUILD_DIR/backend/backend-deploy-production.sh
  skip_cleanup: true
  on:
    branch: deploy
env:
  global:
  - secure: hKgGPPRD/S8GDOXlhFzqUH/cnvHeZYjiIR1qkLdNX0rVTjxZfHyX5Ooi5AN2nd12VIvIZTdybpioiu+GwMj4gRmp9ibrlrqX9VJmwPtAOvwXLzOYZ4ZqYJ+Z+HNXK/aarhR4IYa5IULw3nA1LQORzadmSTf2blETIhnhD72q7f7bA5nAHVXITzHP89o9vH06WXEdc7ihqtSADEOVFXyGucRAgujXreAodvEtjNX9TyTeL8m3FTyysFWzXU81roSskywMGlbHu3jRr1cfTY6k6Z56Uuf+SNAL/TPaVEG46vgPvaSeZeuyS9+vkdT8q3zsgTN2qpMQLMvMBeE+J/JI9XjzgqAD9HIGuEn8rXGFaHOHo61fZdmvyg1fBgiS93N6bdDpNW62Y8bYt2Rr8T9/lYTpMwe8Aq5dxJUpE1kmYwgaRHH9Jj6q5MGxyZl3aG5ZitKjujC4DMYB9Jw2++j07WOIxMRIwMn+H6hyFZc8Izif+fRjF6HHYjabrYBBfd2x+96kr/tBefEqBaixSKF8hKOwqknuZ2h/FrAs4XM0jNtzE2p/ofDKIBsZVuVdNtoSjoGR0+/SBjbrTW3nPp1U7VyVRW4p5RHBaRrTBJ8Bba30Y9vLc6VF4ha3OsXmlg1qlFOMvzfhu/DHBBk6n4iAtUlz+FCLmmN+24CnJCezBqE=
  - secure: k7QSe1COMXm9CmpLrG3biE9qOfzzFFpCuozjDH6en9Qc+BKLWLtBoLQvhavMAX8MMLJ/JY49DIN32ZZyYQroxLRQRXWIlJSuFpPUIiLSLue9wJkkvL4yeWHRHafMwCQJ0Vf0niA3q08WNqpIz86wgVz8A5+Z7bJalK4uPDW+KmULe+cKqxibeINimrB5eqMUD7JDLh6Pl5kmpT9oVpSMYoCUDR9p5Y1/JYuQJ4WYnzHK2wZSLIhkvPLGfSK6i5Td5qX3UhNQlY9NuRgLgV9RSMH/+jtmVCA67hHgPF9pOhcBjVFUXkVob4PyjnPThuexfv9m2d5tjLPnawX8ofbqkshuZ89IOZiC1jvoUnnlsv4sACnuMYL14WQRo7mf5fkAT9M4NwdnkHBtPgc+ZakI2urB9cu0+FSnSUembj/fLQVhPv3IanyRFiW7gLn/iVxMHEgcsNCjWFRxvW8pTdVNOtqK/I2sn3VFJw7Sy2Q+wMM7JOMpjpRxoPO8VoYqPFdHdoJQV5HzNi82CSFVwK8oEbEbu4DnaS5R5cQWj0k5YgtfSDJndPYt1xkVpOrw6EyaCy9CsJC6Ljzi9kHxTiT/dsCNF6EYx6HrKYoUq+whXAjVTxSv0bwtR08mq4f9eNrPEVzCLHVBpFE40ZvHs5VlgKcNOFh9ko2rpS+SfOspvco=
  - secure: IgOEs/7ccXGhgQb3Dfkts98OkX8zD/H1k7evQ4MWLgDb8Vs90BagUPoMxJiaH2O8+ia8A7uDOf+vzTp+P5cT4Y3FKWSU/Vz1k+mu0TjpDJUrNobIxFJXISyJoo7e3k4RY/8YoNYKx1qxt6iB8H7iza1SnPT+tl/jLCN3jG1HKCMj+pCAjfOFyKLQySb+InVVJxbgF8ApVGvNXLXErk+CxonhUTDQYF5XV85pGYkFSkrdXcH/q+RAN+eqGHGabry8S9c2/wh8h7BWD1gd3ySIr2OXHzFdR3yg9h0PUFSwhzwGOe9PyWpXMZ5Qmv+HZ/fcrXH3CVkgyDp0q5x/QNdOBscvanjBSEwdilQ5DRYh10XxEJru6bLceHhwT1epk2U1mIYD/TFbi3qyAHHVavGwBzDWwscvKtd+43BGPewgnblvd76BvAVwQMjL7Kb0mLzp+7KjW6EFYZ43U+C4BDU4q1OaZD9mGSgPvPmaXgyjGCOR7wn+9WTQKbyW7iV2y+Rh1wOa9d3STwN/SNuYvT3EInsyT8Bi7Ym/C7vvc8xLarf6ucHHLYzMShkT9YKqgAGzWWvJo7qaJVLjpyy27e7mIREA4KAMdHSxiyyieKY/47icTQeHZ5mPBL0cSAXd8d8MAVoWXqTkffcVwK5dCkG6CxY36/LQvHZ8TZP7cs5VfRs=
  - secure: R3D6Gb0EoMmlWvN0u5COmRzswE7NHZO+ZAVuJQLxCsgheXeEZr2x8MrS9qMIorJ1dzyWgI8AVtEpWeqH/jl7BHgciAKgNsDT5RAG5vjWTZqcPMet+s5neGKxL3XJj8Vo0Zh021FYpHNTTsUY+k6wLPGexSybtl4VrbvwdyzEZ8sJ/Pl3LpAg6olkX/aVaXaGTYuyp1ohxfvuPQOtZkQ+OPH3AIBr4oy+L49ARFYOd4CpXHvWQjhCHZSMrythhnNHnVGLirGghPl9KJjK7n2uFpbMlYACSxlRfYGyUQQHje5MOvze6z7k/DzosC71c5OS/69Ca92BJcbQW1kwyU1sZ0I6WglS8mW2mUK8lZy0+4MlFjfV5+V9S4YkErQ2V62iaO01RvcWuWEHlxMWlZp2fHRT+Y6RiudsbCm8apWXVbx7oF4wfzbgUQ1hiuy/y67llGLQHX3aB81Malur8TXHxe5EkGZ3CJgANA8I86RVHlYsrxGMDTkNQLy4Gw2tNPTabLeveEgK2eCyjNGuAkGuNS938S05qLCY3QEOnbRIzDW/HgXJ7IBB23W1LNp+K7tgIw9c6I1BxiUdYX3yMHfz+7TdCzEykPNr89SJsd7eQyErwmLp+Nn5Uj0AccNEEc2X/l/3ECc9v9t4YWnUlQUMoRwN9pzWfGKt64lz+KNRaL0=
